#!/usr/bin/env python3
"""Emit data/enemy_model_<account>.json as V9_modules/enemy_model_data.lk.

LeekScript AIs cannot read files at runtime — the enemy model must be baked
into a generated include. Regenerate after any model rebuild, then upload.

IMPORTANT (2026-08-16 CODE_TOO_LARGE incident): the LeekScript compiler puts
ALL global initializers into a single Java method, which javac caps at 64KB
bytecode. A map literal with ~400 entries blows past that (Error 66,
"Invalid AI" on every turn, server-side). So the model is emitted as ONE
string literal and parsed into the ENEMY_MODEL map at AI init instead.
Record format: name|arch|engage|summon|t1m|t2m|t3m  (records joined by ';')

Usage: python3 tools/emit_enemy_model_lk.py [--account main|cure|both]
"""
import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent.parent
DATA = ROOT / "data"
OUT = ROOT / "V9_modules" / "enemy_model_data.lk"

MAX_OPPONENTS = 400  # cap entries; string size stays ~20KB, JVM constant limit is 64KB

FIELD_SEP = "|"
REC_SEP = ";"

PARSE_FN = """
// Parse the raw model string into the ENEMY_MODEL map (runs once at AI init).
function _emParseRaw(raw) {
    var model = [:]
    if (raw == null || raw == '') return model
    var recs = split(raw, ';')
    for (var rec in recs) {
        var f = split(rec, '|')
        if (count(f) < 7) continue
        model[f[0]] = ['arch': f[1], 'engage': number(f[2]), 'summon': number(f[3]),
                       't1m': f[4], 't2m': f[5], 't3m': f[6]]
    }
    return model
}
"""


def lk_str(s):
    return "'" + str(s).replace("\\", "\\\\").replace("'", "\\'") + "'"


def fmt_num(v):
    return f"{float(v):.4g}"


def emit(account):
    path = DATA / f"enemy_model_{account}.json"
    if not path.exists():
        print(f"skip {account}: {path} missing")
        return []
    model = json.load(open(path))
    entries = [(k, v) for k, v in model.items() if not k.startswith("_")]
    # most-fought opponents first
    entries.sort(key=lambda kv: -kv[1].get("fights_analyzed", 0))
    entries = entries[:MAX_OPPONENTS]
    records = []
    for name, e in entries:
        fields = [
            str(name),
            str(e.get("archetype", "bruiser")),
            fmt_num(e.get("mean_engagement_distance") or 0),
            fmt_num(e.get("summon_usage") or 0),
            str(e.get("t1_modal") or ""),
            str(e.get("t2_modal") or ""),
            str(e.get("t3_modal") or ""),
        ]
        if any(FIELD_SEP in f or REC_SEP in f or "\n" in f for f in fields):
            print(f"  WARN: skipping {name!r} (separator char in data)")
            continue
        records.append(FIELD_SEP.join(fields))
    return records


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--account", default="both", choices=["main", "cure", "both"])
    args = ap.parse_args()
    accounts = ["main", "cure"] if args.account == "both" else [args.account]
    records = []
    for acc in accounts:
        records.extend(emit(acc))
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")
    raw = lk_str(REC_SEP.join(records))
    OUT.write_text(
        f"// GENERATED by tools/emit_enemy_model_lk.py on {ts} — do not edit\n"
        f"// Opponent behavioral memory for enemy_model.lk (per-opponent tendencies\n"
        f"// extracted from fight history; rebuild via tools/build_enemy_model.py)\n"
        f"// Emitted as a string + runtime parse: a map literal this size exceeds\n"
        f"// javac's 64KB per-method cap (all global inits share one method).\n"
        f"{PARSE_FN}\n"
        f"global _ENEMY_MODEL_RAW = {raw}\n"
        f"global ENEMY_MODEL = _emParseRaw(_ENEMY_MODEL_RAW)\n"
    )
    print(f"wrote {OUT} with {len(records)} opponent records ({len(raw)} chars)")


if __name__ == "__main__":
    main()
