#!/usr/bin/env python3
"""Emit data/value_model.json as V9_modules/value_model_data.lk —
the MLP forward pass in LeekScript, weights as string literals (same
pattern as the enemy model; avoids the 64KB method cap).

Usage: python3 tools/emit_value_model_lk.py [--model data/value_model.json]
"""
import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).parent.parent
OUT = ROOT / "V9_modules" / "value_model_data.lk"


def fmt(v):
    # fixed-point only: LeekScript number() does not parse scientific
    # notation ("1.5e-05" -> 1.5), which silently mangles small weights.
    v = float(v)
    if v == 0:
        return "0"
    s = f"{v:.10f}".rstrip("0")
    if s.endswith("."):
        s += "0"
    return s


def vec_str(v):
    return ";".join(fmt(x) for x in v)


def mat_str(m):
    return "|".join(";".join(fmt(x) for x in row) for row in m)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=str(ROOT / "data" / "value_model.json"))
    args = ap.parse_args()
    m = json.load(open(args.model))
    ts = datetime.now(timezone.utc).isoformat(timespec="seconds")

    body = f"""// GENERATED by tools/emit_value_model_lk.py on {ts} — do not edit
// MLP value model P(win|state) for the scenario scorer. Weights are string
// literals parsed once at AI init (map-literal emission hits javac's 64KB
// method cap — see 2026-08-16 CODE_TOO_LARGE incident).
// Offline AUC (test): {m.get('auc_test')} vs hp-diff {m.get('auc_hp_diff_test')}

global _VM_MEAN = '{vec_str(m["mean"])}'
global _VM_STD = '{vec_str(m["std"])}'
global _VM_W1 = '{mat_str(m["w"][0])}'
global _VM_B1 = '{vec_str(m["b"][0])}'
global _VM_W2 = '{mat_str(m["w"][1])}'
global _VM_B2 = '{vec_str(m["b"][1])}'
global _VM_W3 = '{mat_str(m["w"][2])}'
global _VM_B3 = '{vec_str(m["b"][2])}'

global _VM_P1 = null
global _VM_P2 = null
global _VM_P3 = null
global _VM_P4 = null

function _vmParseVec(s) {{
    var out = []
    for (var tok in split(s, ';')) push(out, number(tok))
    return out
}}

function _vmParseMat(s) {{
    var out = []
    for (var row in split(s, '|')) push(out, _vmParseVec(row))
    return out
}}

function _vmInit() {{
    if (_VM_P1 == null) {{
        _VM_P1 = [_vmParseVec(_VM_MEAN), _vmParseVec(_VM_STD)]
        _VM_P2 = [_vmParseMat(_VM_W1), _vmParseVec(_VM_B1)]
        _VM_P3 = [_vmParseMat(_VM_W2), _vmParseVec(_VM_B2)]
        _VM_P4 = [_vmParseMat(_VM_W3), _vmParseVec(_VM_B3)]
    }}
}}

// feature vector order (must match tools/train_value_model.py FEATURES+DERIVED):
global VM_FEATURES = '{ ";".join(m["features"]) }'
global VM_DERIVED = 'hp_diff;hp_ratio;sh_diff;maxhp_ratio;poisdpt_diff;str_diff;mag_diff;agi_diff'

// x: array of the 24 raw feature values in VM_FEATURES order. The 8 derived
// features are computed here (train-time order must match
// tools/train_value_model.py DERIVED):
// hp_diff hp_ratio sh_diff maxhp_ratio poisdpt_diff str_diff mag_diff agi_diff
function v9ValuePredict(x) {{
    _vmInit()
    var hpU = x[1], hpF = x[2]
    var shU = x[6] + x[8], shF = x[7] + x[9]
    var full = x
    push(full, hpU - hpF)
    push(full, hpU / max(0.01, hpF))
    push(full, shU - shF)
    push(full, x[3] / max(1, x[4]))
    push(full, x[12] - x[13])
    push(full, x[14] - x[15])
    push(full, x[16] - x[17])
    push(full, x[18] - x[19])
    // archetype flags (calibration audit 2026-08-18)
    push(full, (x[23] >= 300 && x[25] >= 200) ? 1.0 : 0.0)
    push(full, (x[15] >= 400 && x[23] < 300) ? 1.0 : 0.0)
    push(full, x[21] >= 400 ? 1.0 : 0.0)
    var mn = _VM_P1[0], sd = _VM_P1[1]
    var h = []
    for (var i = 0; i < count(full); i++) push(h, (full[i] - mn[i]) / sd[i])
    // layer 1 (relu)
    var h1 = []
    for (var j = 0; j < count(_VM_P2[1]); j++) {{
        var z = _VM_P2[1][j]
        for (var i = 0; i < count(h); i++) z += _VM_P2[0][i][j] * h[i]
        push(h1, z > 0 ? z : 0)
    }}
    // layer 2 (relu)
    var h2 = []
    for (var j2 = 0; j2 < count(_VM_P3[1]); j2++) {{
        var z2 = _VM_P3[1][j2]
        for (var i2 = 0; i2 < count(h1); i2++) z2 += _VM_P3[0][i2][j2] * h1[i2]
        push(h2, z2 > 0 ? z2 : 0)
    }}
    // out (sigmoid)
    var z3 = _VM_P4[1][0]
    for (var i3 = 0; i3 < count(h2); i3++) z3 += _VM_P4[0][i3][0] * h2[i3]
    return 1.0 / (1.0 + exp(-z3))
}}
"""
    OUT.write_text(body)
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
