#!/usr/bin/env python3
"""Export the sign-constrained value model to LeekScript (2026-09-28).

Reads data/prod/value_mono.json + the feature layout from
tools/value_dataset.py and writes V9_modules/value_net_data.lk: weights,
scaler and the feature layout (effect type -> group, group scales, order),
so the LeekScript feature builder (value_net.lk) cannot drift from training.

    python3 tools/value_export_lk.py
"""
import json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import value_dataset as vd

SRC = os.path.join(ROOT, 'data', 'prod', 'value_mono.json')
DST = os.path.join(ROOT, 'V9_modules', 'value_net_data.lk')


def num(x):
    # plain decimals: LeekScript number() does not parse exponents ('1e-05')
    s = ('%.7f' % x).rstrip('0').rstrip('.')
    return '0' if s in ('', '-0', '-') else s


def arr(v):
    if isinstance(v, list) and v and isinstance(v[0], list):
        return '[' + ', '.join(arr(r) for r in v) + ']'
    return '[' + ', '.join(num(x) for x in v) + ']'


def sv(v):
    """String-encoded weights (';' columns, '|' rows), parsed once at init:
    large array literals exceed javac's 64 KB method cap (CODE_TOO_LARGE)."""
    if isinstance(v, list) and v and isinstance(v[0], list):
        return "'" + '|'.join(';'.join(num(x) for x in r) for r in v) + "'"
    return "'" + ';'.join(num(x) for x in v) + "'"


def main():
    m = json.load(open(SRC))
    names = m['names']
    assert names == vd.NAMES, 'feature layout drifted from value_dataset.py'
    groups = vd.GROUPS
    gidx = {g: i for i, g in enumerate(groups)}
    ctx_idx = [names.index(n) for n in m['ctx']]
    mono_idx = [names.index(n) for n in m['mono']]
    (W1, b1), (W2, b2), (W3, b3) = m['layers']
    lines = [
        '// GENERATED by tools/value_export_lk.py from data/prod/value_mono.json - do not edit.',
        '// Sign-constrained prod value model: P(win | state at the start of my turn).',
        '// %d features (%d context, %d monotone); layer sizes %d-%d-%d-%d.' % (
            len(names), len(ctx_idx), len(mono_idx), len(W1), len(W1[0]), len(W2[0]), len(W3[0])),
        'global __vnNFeat = %d' % len(names),
        'global __vnNGroups = %d' % len(groups),
        '// effect type -> group index (engine Effect.TYPE_*)',
        'global __vnGroupOf = [' + ', '.join('%d: %d' % (t, gidx[g]) for t, g in sorted(vd.GROUP.items())) + ']',
        'global __vnGScale = ' + arr([vd.GSCALE.get(g, 100.0) for g in groups]),
        'global __vnGPoison = %d' % gidx['poison'],
        'global __vnGBufStr = %d' % gidx['buf_str'],
        'global __vnGroupNames = [' + ', '.join('"%s"' % g for g in groups) + ']',
        'global __vnS_Mu = ' + sv(m['mu']),
        'global __vnS_Sd = ' + sv(m['sd']),
        'global __vnClip = %s' % num(m['clip']),
        'global __vnCtxIdx = [' + ', '.join(str(i) for i in ctx_idx) + ']',
        'global __vnMonoIdx = [' + ', '.join(str(i) for i in mono_idx) + ']',
        'global __vnS_Sign = ' + sv(m['sign']),
        'global __vnS_W1 = ' + sv(W1), 'global __vnS_B1 = ' + sv(b1),
        'global __vnS_W2 = ' + sv(W2), 'global __vnS_B2 = ' + sv(b2),
        'global __vnS_W3 = ' + sv(W3), 'global __vnS_B3 = ' + sv(b3),
        '',
    ]
    open(DST, 'w').write('\n'.join(lines))
    print('wrote %s (%d bytes)' % (DST, os.path.getsize(DST)))


if __name__ == '__main__':
    main()
